# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QLabel, QLineEdit
from functools import partial
from listops import *
from testSubject import *

class Ui_MainWindow(object):

    def setupUi(self, MainWindow, size, list):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(840, 800))
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setStatusTip("")
        self.centralwidget.setWhatsThis("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.chemtabs = QtWidgets.QTabWidget(self.centralwidget)
        self.chemtabs.setObjectName("chemtabs")
        self.Main = QtWidgets.QWidget()
        self.Main.setStatusTip("")
        self.Main.setWhatsThis("")
        self.Main.setAccessibleName("")
        self.Main.setAccessibleDescription("")
        self.Main.setObjectName("Main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Main)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.Main)
        self.frame.setStatusTip("")
        self.frame.setWhatsThis("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(101, 250))
        self.frame_2.setMaximumSize(QtCore.QSize(150, 800))
        self.frame_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_2.setBaseSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setMinimumSize(QtCore.QSize(100, 250))
        self.listWidget.setMaximumSize(QtCore.QSize(150, 800))
        self.listWidget.setMouseTracking(True)
        #self.listWidget.setTabletTracking(True)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setIconSize(QtCore.QSize(10, 10))
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setGridSize(QtCore.QSize(10, 20))
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(True)
        #self.listWidget.setItemAlignment(QtCore.Qt.AlignLeading)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.itemClicked.connect(partial(self.loadchemtotextedit, list))
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Searchbar1 = QtWidgets.QLineEdit(self.frame)
        self.Searchbar1.setMinimumSize(QtCore.QSize(175, 0))
        self.Searchbar1.setToolTip("")
        self.Searchbar1.setStatusTip("")
        self.Searchbar1.setReadOnly(False)
        self.Searchbar1.setObjectName("Searchbar1")
        self.horizontalLayout.addWidget(self.Searchbar1)
        self.searchButton = QtWidgets.QPushButton(self.frame)
        self.searchButton.setMinimumSize(QtCore.QSize(50, 50))
        self.searchButton.setMaximumSize(QtCore.QSize(500, 50))
        self.searchButton.setToolTip("")
        self.searchButton.setIconSize(QtCore.QSize(20, 20))
        self.searchButton.setObjectName("searchButton")
        self.searchButton.clicked.connect(partial(self.searchButtonclicked,list))
        self.horizontalLayout.addWidget(self.searchButton)
        self.checkoutButton = QtWidgets.QPushButton(self.frame)
        self.checkoutButton.setMinimumSize(QtCore.QSize(50, 50))
        self.checkoutButton.setToolTip("")
        self.checkoutButton.setObjectName("checkoutButton")
        self.checkoutButton.clicked.connect(self.checkoutButtonclicked)
        self.horizontalLayout.addWidget(self.checkoutButton)
        self.checkinButton = QtWidgets.QPushButton(self.frame)
        self.checkinButton.setMinimumSize(QtCore.QSize(50, 50))
        self.checkinButton.setToolTip("")
        self.checkinButton.setObjectName("checkinButton")
        self.checkinButton.clicked.connect(self.checkinButtonclicked)
        self.horizontalLayout.addWidget(self.checkinButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outputfileButton = QtWidgets.QPushButton(self.frame)
        self.outputfileButton.setMinimumSize(QtCore.QSize(150, 50))
        self.outputfileButton.setObjectName("outputfileButton")
        self.outputfileButton.clicked.connect(self.outputfileButtonclicked)
        self.horizontalLayout_3.addWidget(self.outputfileButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TextEdit = QtWidgets.QTextEdit(self.frame)
        self.TextEdit.setObjectName("TextEdit")
        self.gridLayout_3.addWidget(self.TextEdit, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.deleteButton = QtWidgets.QPushButton(self.frame)
        self.deleteButton.setMinimumSize(QtCore.QSize(0, 50))
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.clicked.connect(partial(self.deleteButtonclicked,list))
        self.horizontalLayout_5.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.chemtabs.addTab(self.Main, "")
        self.Addnewchem = QtWidgets.QWidget()
        self.Addnewchem.setObjectName("Addnewchem")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Addnewchem)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.Addnewchem)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_11.addWidget(self.lineEdit_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.saveButton = QtWidgets.QPushButton(self.frame_3)
        self.saveButton.setObjectName("saveButton")
        self.saveButton.clicked.connect(self.saveButtonclicked)
        self.horizontalLayout_12.addWidget(self.saveButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        self.chemtabs.addTab(self.Addnewchem, "")
        self.EditChem = QtWidgets.QWidget()
        self.EditChem.setObjectName("EditChem")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.EditChem)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.EditChem)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_14.addWidget(self.lineEdit_7)
        self.search2Button = QtWidgets.QPushButton(self.frame_4)
        self.search2Button.setObjectName("search2Button")
        self.search2Button.clicked.connect(self.search2Buttonclicked)
        self.horizontalLayout_14.addWidget(self.search2Button)
        self.gridLayout_6.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_16.addWidget(self.textEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.editButton = QtWidgets.QPushButton(self.frame_4)
        self.editButton.setObjectName("editButton")
        self.editButton.clicked.connect(self.editButtonclicked)
        self.horizontalLayout_17.addWidget(self.editButton)
        self.save2Button = QtWidgets.QPushButton(self.frame_4)
        self.save2Button.setObjectName("saveButton")
        self.save2Button.clicked.connect(self.save2Buttonclicked)
        self.horizontalLayout_17.addWidget(self.save2Button)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 1, 1, 1)
        self.chemtabs.addTab(self.EditChem, "")
        self.gridLayout.addWidget(self.chemtabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.appendlist(size, list)
        self.chemtabs.setCurrentIndex(0)
        self.listWidget.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chemventory MainWindow"))
        self.listWidget.setSortingEnabled(True)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.checkoutButton.setText(_translate("MainWindow", "Check out"))
        self.checkinButton.setText(_translate("MainWindow", "Check In"))
        self.outputfileButton.setText(_translate("MainWindow", "Create Output File"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Entry"))
        self.chemtabs.setTabText(self.chemtabs.indexOf(self.Main), _translate("MainWindow", "Main Tab"))
        self.label.setText(_translate("MainWindow", "Name of Chemical:"))
        self.label_2.setText(_translate("MainWindow", "Mass in grams:"))
        self.label_3.setText(_translate("MainWindow", "Date Received:"))
        self.label_4.setText(_translate("MainWindow", "Type of Chemical"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Acid"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Base"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Oxidizer"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Metals"))
        self.label_5.setText(_translate("MainWindow", "Chemical Formula:"))
        self.label_6.setText(_translate("MainWindow", "Supplier:"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.chemtabs.setTabText(self.chemtabs.indexOf(self.Addnewchem), _translate("MainWindow", "New Entry"))
        self.label_7.setText(_translate("MainWindow", "Chemical:"))
        self.search2Button.setText(_translate("MainWindow", "Search"))
        self.editButton.setText(_translate("MainWindow", "Edit Entry"))
        self.save2Button.setText(_translate("MainWindow", "Save Entry"))
        self.chemtabs.setTabText(self.chemtabs.indexOf(self.EditChem), _translate("MainWindow", "Edit Entries"))

    def appendlist(self, size, list):
        # fills out the list with all the chemicals
        for i in range(size):
            item = QtWidgets.QListWidgetItem()
            self.listWidget.setCurrentRow(i)
            self.listWidget.addItem(list[i].name)
            item = self.listWidget.item(i)
            item.setText(list[i].name)

    def loadchemtotextedit(self, list1, item):

        # the found chemical object
        foundchem = searchList(list1,str(item.text()))

        chemfile = open("tempfile.txt", 'w')

        chemfile.write("Chemical Name: " + foundchem.name + "\n \n")
        chemfile.write("Chemical Formula: " + foundchem.formula + "\n \n")
        chemfile.write("Chemical Supplier: " + foundchem.supplier + "\n \n")
        chemfile.write("Chemical Initial Mass: " + str(foundchem.massI) + "\n \n")
        chemfile.write("Chemical Last Mass: " + str(foundchem.massUpdate) + "\n \n")
        chemfile.write("Chemical age: " + str(foundchem.age) + "\n \n")
        chemfile.write("Barcode Number: " + str(foundchem.barC) + "\n \n")
        if foundchem.insys == 1:
            chemfile.write("Check in/out status: " + "Checked in" + "\n")
        else:
            chemfile.write("Check in/out status: " + "Checked out" + "\n")

        chemfile.close()

        text = open('tempfile.txt').read()
        self.TextEdit.setPlainText(text)

    def searchButtonclicked(self, list1):
        #take text from text bar in and erase text field
        searchstr = self.Searchbar1.text()

        if searchstr == "AARON":
            inherit = testSubject()

            chemfile = open("tempfile.txt", 'w')

            chemfile.write("Chemical Name: " + inherit.name + "\n \n")
            chemfile.write("Chemical Formula: " + inherit.formula + "\n \n")
            chemfile.write("Chemical Supplier: " + inherit.supplier + "\n \n")
            chemfile.write("Chemical Initial Mass: " + str(inherit.massI) + "\n \n")
            chemfile.write("Chemical Last Mass: " + str(inherit.massUpdate) + "\n \n")
            chemfile.write("Chemical age: " + str(inherit.age) + "\n \n")
            chemfile.write("Barcode Number: " + str(inherit.barC) + "\n \n")
            if inherit.insys == 1:
                chemfile.write("Check in/out status: " + "Checked in" + "\n \n")
            else:
                chemfile.write("Check in/out status: " + "Checked out" + "\n \n")

            chemfile.write("Purpose: " + inherit.purpose + "\n")

            chemfile.close()

            text = open('tempfile.txt').read()
            self.TextEdit.setPlainText(text)
        else:
            # the found chemical object
            foundchem = searchList(list1,searchstr)

            chemfile = open("tempfile.txt", 'w')

            chemfile.write("Chemical Name: " + foundchem.name + "\n \n")
            chemfile.write("Chemical Formula: " + foundchem.formula + "\n \n")
            chemfile.write("Chemical Supplier: " + foundchem.supplier + "\n \n")
            chemfile.write("Chemical Initial Mass: " + str(foundchem.massI) + "\n \n")
            chemfile.write("Chemical Last Mass: " + str(foundchem.massUpdate) + "\n \n")
            chemfile.write("Chemical age: " + str(foundchem.age) + "\n \n")
            chemfile.write("Barcode Number: " + str(foundchem.barC) + "\n \n")
            if foundchem.insys == 1:
                chemfile.write("Check in/out status: " + "Checked in" + "\n")
            else:
                chemfile.write("Check in/out status: " + "Checked out" + "\n")

            chemfile.close()

            text = open('tempfile.txt').read()
            self.TextEdit.setPlainText(text)

    def checkoutButtonclicked(self, list1):
        searchstr = self.Searchbar1.text()

        foundchem = searchList(list1,searchstr)

        # light LED
        # make user weigh it and record weight

        foundchem.setinsys(0)

    def checkinButtonclicked(self, list1):
        searchstr = self.Searchbar1.text()

        foundchem = searchList(list1,searchstr)

        # make user weigh it and record weight
        # light LED

        foundchem.setinsys(1)

    def outputfileButtonclicked(self):
        print("output file")

    def deleteButtonclicked(self, list1):
        searchstr = self.Searchbar1.text()


        foundchem = searchList(list1,searchstr)

        removeFromList(list1,foundchem)



    def saveButtonclicked(self):
        print("save")

    def search2Buttonclicked(self):
        print("search 2")

    def editButtonclicked(self):
        print("edit")

    def save2Buttonclicked(self):
        print("save")
